_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 3
                - 11
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 3
                - 11
                - 41
                - 49
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.2
            "6": 4.45.0
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
monitor_gpus:
    value: true
